import ddf.minim.*;
Minim minim;
AudioPlayer player;
PImage fondo;
PImage logo;
PImage anakin;
PImage obiwan;
PImage padme;
PImage palpatine;
PImage willy;
PImage george;
int posylogo=540;
int posyanakin=1150;
int posyobiwan=1150;
int posypadme=1650;
int posypalpatine=1650;
int posywilly=2350;
int posygeorge=3000;
int postexto1;
int postexto2;
int postexto3;
int postexto4;
int postexto5;
int postexto6;
int postexto7;
int postexto8;
int postexto9;
//float tamanoTexto;
PFont mifuente;
void setup(){
  size(960,540);
  fondo = loadImage("Fondo.png");
  logo = loadImage("Logo.png");
  anakin = loadImage ("anakin.png");
  obiwan = loadImage ("obiwan.png");
  padme = loadImage ("padme.png");
  palpatine = loadImage("palpatine.png");
  willy = loadImage("willy.jpg");
  george = loadImage("george.jpg");
  frameRate( 30 );
  //tamanoTexto = 20;
  postexto1=1100;
  postexto2=1600;
  postexto3=1600;
  postexto4=2100;
  postexto5=2100;
  postexto6=2250;
  postexto7=2700;
  postexto8=2900;
  postexto9=3350;
  mifuente = loadFont("YuGothic-Bold-48.vlw");
  minim = new Minim(this);
  player = minim.loadFile("jedi.mp3");
  player.play();
}
void draw() {
 background( fondo );
  image(logo, 80, posylogo);
  posylogo=posylogo-3;
  textAlign( CENTER );
  textFont(mifuente);
  fill( 10, 169, 236 );
  textSize( 20 );
  text( "Protagonistas", width/2, postexto1 );
  postexto1=postexto1-2;
  textSize(30);
  text("Anakin Skywalker", width/4, postexto2 );
  postexto2=postexto2-2;
  image(anakin, 50, posyanakin);
  posyanakin=posyanakin-2;
  textSize(30);
  text("Obi-Wan Kenobi", 720, postexto3);
  postexto3=postexto3-2;
  image(obiwan,500,posyobiwan);
  posyobiwan=posyobiwan-2;
  textSize(30);
  text("Padmé Amidala", width/4, postexto4 );
  postexto4=postexto4-2;
  image(padme, 50, posypadme);
  posypadme=posypadme-2;
  textSize(30);
  
  text("Sheev Palpatine", 720, postexto5);
  postexto5=postexto5-2;
  image(palpatine,500, posypalpatine);
  posypalpatine=posypalpatine-2;
  textSize( 20 );
  text( "Música", width/2, postexto6 );
  postexto6=postexto6-2;
  textSize( 30 );
  text( "John Williams", width/2, postexto7 );
  postexto7=postexto7-2;
  image(willy,325, posywilly);
  posywilly=posywilly-2;
  textSize(20);
  text("Dirección",width/2, postexto8);
  postexto8=postexto8-2;
  image(george,325, posygeorge);
  posygeorge=posygeorge-2;
  textSize(30);
  text("George Lucas", width/2, postexto9);
  postexto9=postexto9-2;}
